services:
  postgres:
    image: postgres:13
    volumes:
      - ./migrations/create.sql:/docker-entrypoint-init db.d/create.sql
    environment:
      POSTGRES_DB: "cinematograph"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"